### ISSUE TITLE
Lack of DisplayNameComponent can cause log spam in PotionClientSystem

### ISSUE THREAD

**Issue by Cervator** [Terasology/Potions#45]
If at present you `give emptyVial` with Potions running you get a broken icon image in the toolbar (as there is no texture - I suspect `emptyvial.prefab` is obsolete and should be deleted) followed by massive log spam as seemingly a tooltip preparation piece fails to find a display name for the broken vial, causing NPEs over and over.

Can fix by simply adding a `DisplayName` block to that prefab, but instead we should really null harden `PotionClientSystem.setItemTooltip()` so this can't happen, then maybe delete `emptyvial.prefab`

```
17:14:20.877 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.potions.system.PotionClientSystem.setItemTooltip(PotionClientSystem.java:44)
	at org.terasology.potions.system.PotionClientSystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemCell$1.get(ItemCell.java:58)
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemCell$1.get(ItemCell.java:47)
	at org.terasology.rendering.nui.widgets.UIList.getList(UIList.java:132)
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemIcon.getTooltip(ItemIcon.java:158)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:401)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:368)
	at org.terasology.rendering.nui.layers.ingame.inventory.ItemCell.onDraw(ItemCell.java:111)
	at org.terasology.rendering.nui.layers.ingame.inventory.InventoryCell.onDraw(InventoryCell.java:97)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.layouts.FlowLayout.onDraw(FlowLayout.java:57)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:78)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.layers.hud.CoreHudWidget.onDraw(CoreHudWidget.java:60)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.layers.hud.HUDScreenLayer.onDraw(HUDScreenLayer.java:162)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
	at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
	at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:476)
	at org.terasology.engine.modes.StateIngame.renderUserInterface(StateIngame.java:235)
	at org.terasology.engine.modes.StateIngame.render(StateIngame.java:219)
	at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:189)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:441)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:397)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:373)
	at org.terasology.engine.Terasology.main(Terasology.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by xrtariq2594** [comment]
Alright, that should fix the issue @Cervator.
